In [145]:
import pandas as pd
import numpy as np
from datetime import datetime

In [146]:
costs=pd.read_csv(r'E:\Data Mining\PSet4\data\raw\costs_us.csv')
orders=pd.read_csv(r'E:\Data Mining\PSet4\data\raw\orders_log_us.csv')
visits=pd.read_csv(r'E:\Data Mining\PSet4\data\raw\visits_log_us.csv')

In [147]:
def initialExploration(df):
    print(30*'='+'First 10 rows'+'='*30)
    print(df.head(10))
    print(30*'='+'Last 10 rows'+'='*30)
    print(df.tail(10))
    print(30*'='+'Info'+'='*30)
    print(df.info())
    print(30*'='+'Nulls'+'='*30)
    print(df.isnull().sum())
    print(30*'='+'Duplicates'+'='*30)
    print(df.duplicated().sum())

In [148]:
initialExploration(costs)

==============================First 10 rows==============================
   source_id          dt  costs
0          1  2017-06-01  75.20
1          1  2017-06-02  62.25
2          1  2017-06-03  36.53
3          1  2017-06-04  55.00
4          1  2017-06-05  57.08
5          1  2017-06-06  40.39
6          1  2017-06-07  40.59
7          1  2017-06-08  56.63
8          1  2017-06-09  40.16
9          1  2017-06-10  43.24
==============================Last 10 rows==============================
      source_id          dt  costs
2532         10  2018-05-22  21.70
2533         10  2018-05-23   7.42
2534         10  2018-05-24  10.79
2535         10  2018-05-25  22.21
2536         10  2018-05-26   7.89
2537         10  2018-05-27   9.92
2538         10  2018-05-28  21.26
2539         10  2018-05-29  11.32
2540         10  2018-05-30  33.15
2541         10  2018-05-31  17.60
==============================Info==============================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   source_id  2542 non-null   int64
 1   dt         2542 non-null   object
 2   costs      2542 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 59.7+ KB
None
==============================Nulls==============================
source_id    0
dt           0
costs        0
dtype: int64
==============================Duplicates==============================
0

In [149]:
initialExploration(orders)

==============================First 10 rows==============================
                Buy Ts  Revenue                   Uid
0  2017-06-01 00:10:00    17.00  10329302124590727494
1  2017-06-01 00:25:00     0.55  11627257723692907447
2  2017-06-01 00:27:00     0.37  17903680561304213844
3  2017-06-01 00:29:00     0.55  16109239769442553005
4  2017-06-01 07:58:00     0.37  14200605875248379450
5  2017-06-01 08:43:00     0.18  10402394430196413321
6  2017-06-01 08:54:00     1.83  12464626743129688638
7  2017-06-01 09:22:00     1.22   3644482766749211722
8  2017-06-01 09:22:00     3.30  17542070709969841479
9  2017-06-01 09:23:00     0.37   1074355127080856382
==============================Last 10 rows==============================
                    Buy Ts  Revenue                   Uid
50405  2018-05-31 23:36:00     0.61   1551265230644458155
50406  2018-05-31 23:40:00     1.16  13121453305610619664
50407  2018-05-31 23:40:00     2.26  15576344609395725707
50408  2018-05-31 23:42:00     0.92  15854392578508828030
50409  2018-05-31 23:43:00     3.67   1805512004303848280
50410  2018-05-31 23:50:00     4.64  12296626599487328624
50411  2018-05-31 23:50:00     5.80  11369640365507475976
50412  2018-05-31 23:54:00     0.30   1786462140797698849
50413  2018-05-31 23:56:00     3.67   3993697860786194247
50414  2018-06-01 00:02:00     3.42     83872787173869366
==============================Info==============================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50415 entries, 0 to 50414
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Buy Ts   50415 non-null  object
 1   Revenue  50415 non-null  float64
 2   Uid      50415 non-null  uint64
dtypes: float64(1), object(1), uint64(1)
memory usage: 1.2+ MB
None
==============================Nulls==============================
Buy Ts     0
Revenue    0
Uid        0
dtype: int64
==============================Duplicates==============================
0

In [150]:
initialExploration(visits)

==============================First 10 rows==============================
    Device               End Ts  Source Id             Start Ts  \
0    touch  2017-12-20 17:38:00          4  2017-12-20 17:20:00
1  desktop  2018-02-19 17:21:00          2  2018-02-19 16:53:00
2    touch  2017-07-01 01:54:00          5  2017-07-01 01:54:00
3  desktop  2018-05-20 11:23:00          9  2018-05-20 10:59:00
4  desktop  2017-12-27 14:06:00          3  2017-12-27 14:06:00
5  desktop  2017-09-03 21:36:00          5  2017-09-03 21:35:00
6  desktop  2018-01-30 12:09:00          1  2018-01-30 11:13:00
7    touch  2017-11-05 15:15:00          3  2017-11-05 15:14:00
8  desktop  2017-07-19 10:44:00          3  2017-07-19 10:41:00
9  desktop  2017-11-08 13:43:00          5  2017-11-08 13:42:00

                    Uid
0  16879256277535980062
1    104060357244891740
2   7459035603376831527
3  16174680259334210214
4   9969694820036681168
5  16007536194108375387
6   6661610529277171451
7  11423865690854540312
8   2987360259350925644
9   1289240080042562063
==============================Last 10 rows==============================
         Device               End Ts  Source Id             Start Ts  \
359390  desktop  2017-12-11 17:54:19          1  2017-12-11 17:54:00
359391    touch  2017-08-30 11:53:19          2  2017-08-30 11:53:00
359392  desktop  2017-12-30 21:49:19          4  2017-12-30 21:49:00
359393  desktop  2017-06-08 07:49:19          4  2017-06-08 07:49:00
359394    touch  2017-11-06 08:00:19          4  2017-11-06 08:00:00
359395  desktop  2017-07-29 19:07:19          2  2017-07-29 19:07:00
359396    touch  2018-01-25 17:38:19          1  2018-01-25 17:38:00
359397  desktop  2018-03-03 10:12:19          4  2018-03-03 10:12:00
359398  desktop  2017-11-02 10:12:19          5  2017-11-02 10:12:00
359399    touch  2017-09-10 13:13:19          2  2017-09-10 13:13:00

                         Uid
359390  18268369011883553090
359391  18304232853749481866
359392  18311497973035795342
359393  18325675073358289850
359394  18332905065174083046
359395  18363291481961487539
359396  18370831553019119586
359397  18387297585500748294
359398  18388616944624776485
359399  18396128934054549559
==============================Info==============================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359400 entries, 0 to 359399
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Device     359400 non-null  object
 1   End Ts     359400 non-null  object
 2   Source Id  359400 non-null  int64
 3   Start Ts   359400 non-null  object
 4   Uid        359400 non-null  uint64
dtypes: int64(1), object(3), uint64(1)
memory usage: 13.7+ MB
None
==============================Nulls==============================
Device       0
End Ts       0
Source Id    0
Start Ts     0
Uid          0
dtype: int64
==============================Duplicates==============================
0

No duplicates in any of these dataframes and no null values

In [151]:
def changeToDateTime(df,column):
    df[column]=pd.to_datetime(df[column])

In [152]:
def standarize_columns(cols):
    cols = cols.str.lower()
    cols = cols.str.replace(' ', '_')
    cols = cols.str.replace('(', '')
    cols = cols.str.replace(')', '')
    return cols

In [153]:
costs.columns=standarize_columns(costs.columns)
orders.columns=standarize_columns(orders.columns)
visits.columns=standarize_columns(visits.columns)

In [154]:
changeToDateTime(costs,'dt')

In [155]:
costsPerDay=costs.groupby(costs['dt']).sum().reset_index()
costsPerDay

            dt  source_id    costs
0   2017-06-01         34   735.26
1   2017-06-02         34   721.19
2   2017-06-03         34   450.85
3   2017-06-04         34   761.16
4   2017-06-05         34   821.44
..         ...        ...      ...
359 2018-05-27         34   532.87
360 2018-05-28         34   619.44
361 2018-05-29         34   784.79
362 2018-05-30         34  1183.00
363 2018-05-31         34  2153.70

[364 rows x 3 columns]

In [156]:
orders

                    buy_ts  revenue                   uid
0      2017-06-01 00:10:00    17.00  10329302124590727494
1      2017-06-01 00:25:00     0.55  11627257723692907447
2      2017-06-01 00:27:00     0.37  17903680561304213844
3      2017-06-01 00:29:00     0.55  16109239769442553005
4      2017-06-01 07:58:00     0.37  14200605875248379450
...                    ...      ...                   ...
50410  2018-05-31 23:50:00     4.64  12296626599487328624
50411  2018-05-31 23:50:00     5.80  11369640365507475976
50412  2018-05-31 23:54:00     0.30   1786462140797698849
50413  2018-05-31 23:56:00     3.67   3993697860786194247
50414  2018-06-01 00:02:00     3.42     83872787173869366

[50415 rows x 3 columns]

In [157]:
changeToDateTime(orders,'buy_ts')

In [158]:
changeToDateTime(visits,'end_ts')
changeToDateTime(visits,'start_ts')

In [159]:
visits.head(5)

,device,end_ts,source_id,start_ts,uid
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168

In [160]:
print('Min_start_ts:',visits['start_ts'].min())
print('Max_start_ts:',visits['start_ts'].max())
print('Min_end_ts:',visits['end_ts'].min())
print('Max_end_ts',visits['end_ts'].max())

Min_start_ts: 2017-06-01 00:01:00
Max_start_ts: 2018-05-31 23:59:00
Min_end_ts: 2017-06-01 00:02:00
Max_end_ts 2018-06-01 01:26:00

In [161]:
visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359400 entries, 0 to 359399
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   device     359400 non-null  object
 1   end_ts     359400 non-null  datetime64[ns]
 2   source_id  359400 non-null  int64
 3   start_ts   359400 non-null  datetime64[ns]
 4   uid        359400 non-null  uint64
dtypes: datetime64[ns](2), int64(1), object(1), uint64(1)
memory usage: 13.7+ MB

## DAU, WAU , MAU

Agregamos fechas en base a dia, semana, y mes de 'start_ts' para posteriormente luego realizar el conteo de visitas por dia, semana o mes unicos por usuario

In [162]:
visits['start_ts_date'] = visits['start_ts'].dt.date
visits['start_ts_week']=visits['start_ts'].dt.isocalendar().week
visits['start_ts_month']=visits['start_ts'].dt.strftime('%Y-%m-01')

In [163]:
visits

,device,end_ts,source_id,start_ts,uid,start_ts_date,start_ts_week,start_ts_month
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,2017-12-20,51,2017-12-01
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,2018-02-19,8,2018-02-01
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,2017-07-01,26,2017-07-01
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,2018-05-20,20,2018-05-01
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,2017-12-27,52,2017-12-01
...,...,...,...,...,...,...,...,...
359395,desktop,2017-07-29 19:07:19,2,2017-07-29 19:07:00,18363291481961487539,2017-07-29,30,2017-07-01
359396,touch,2018-01-25 17:38:19,1,2018-01-25 17:38:00,18370831553019119586,2018-01-25,4,2018-01-01
359397,desktop,2018-03-03 10:12:19,4,2018-03-03 10:12:00,18387297585500748294,2018-03-03,9,2018-03-01
359398,desktop,2017-11-02 10:12:19,5,2017-11-02 10:12:00,18388616944624776485,2017-11-02,44,2017-11-01
359399,touch,2017-09-10 13:13:19,2,2017-09-10 13:13:00,18396128934054549559,2017-09-10,36,2017-09-01

### DAU

In [164]:
visitsPerDay=visits.groupby('start_ts_date').agg({'uid':['count','nunique']})
visitsPerDay.columns=['n_visitas','n_personas']
visitsPerDay

               n_visitas  n_personas
start_ts_date
2017-06-01           664         605
2017-06-02           658         608
2017-06-03           477         445
2017-06-04           510         476
2017-06-05           893         820
...                  ...         ...
2018-05-27           672         620
2018-05-28          1156        1039
2018-05-29          1035         948
2018-05-30          1410        1289
2018-05-31          2256        1997

[364 rows x 2 columns]

Al realizar un groupby por cada dia en este caso podemos encontrar el numero de sesiones y usuarios por cada dia del dataset.

### MAU

In [165]:
visits

,device,end_ts,source_id,start_ts,uid,start_ts_date,start_ts_week,start_ts_month
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,2017-12-20,51,2017-12-01
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,2018-02-19,8,2018-02-01
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,2017-07-01,26,2017-07-01
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,2018-05-20,20,2018-05-01
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,2017-12-27,52,2017-12-01
...,...,...,...,...,...,...,...,...
359395,desktop,2017-07-29 19:07:19,2,2017-07-29 19:07:00,18363291481961487539,2017-07-29,30,2017-07-01
359396,touch,2018-01-25 17:38:19,1,2018-01-25 17:38:00,18370831553019119586,2018-01-25,4,2018-01-01
359397,desktop,2018-03-03 10:12:19,4,2018-03-03 10:12:00,18387297585500748294,2018-03-03,9,2018-03-01
359398,desktop,2017-11-02 10:12:19,5,2017-11-02 10:12:00,18388616944624776485,2017-11-02,44,2017-11-01
359399,touch,2017-09-10 13:13:19,2,2017-09-10 13:13:00,18396128934054549559,2017-09-10,36,2017-09-01

In [166]:
visitsPerMonth=visits.groupby('start_ts_week').agg({'uid':['count','nunique']})
visitsPerMonth.columns=['n_visitas','n_usuarios']
visitsPerMonth

               n_visitas  n_usuarios
start_ts_week
1                   8057        6918
2                   7871        6703
3                   8317        6972
4                   8488        7060
5                   9796        8111
6                   9407        7908
7                   9272        7759
8                   8930        7518
9                   8771        7395
10                  8147        6844
11                  7489        6225
12                  9393        7898
13                  5862        4940
14                  6242        5383
15                  6382        5494
16                  6768        5740
17                  6574        5503
18                  4496        3916
19                  4803        4128
20                  6094        5070
21                  5934        4995
22                  8166        6867
23                  4931        4129
24                  3214        2812
25                  3273        2878
26                  3514        3064
27                  3822        3294
28                  5105        4355
29                  4574        3841
30                  3072        2655
31                  2729        2364
32                  2782        2444
33                  3128        2746
34                  3585        3116
35                  4296        3694
36                  5115        4412
37                  5011        4319
38                  5715        4874
39                  7315        6241
40                  8878        7612
41                  8317        7074
42                  8336        7148
43                  8712        7401
44                  8645        7480
45                  8287        7179
46                  9656        8117
47                 13572       10586
48                 10409        8166
49                 10298        8407
50                 10120        8214
51                  8500        7172
52                  9230        7774

Si nos enfocamos en el 'n_usuarios' podemos sacar el numero de usuarios uniicos que visitaron en esta semana. La columna de 'n_visitas' son las visitas totales en esa semana

### MAU

In [167]:
visitsPerMonth=visits.groupby('start_ts_month').agg({'uid':['count','nunique']})
visitsPerMonth.columns=['n_visitas','n_usarios']

Si nos enfocamos en el 'n_usuarios' podemos sacar el numero de usuarios unicos que visitaron en este mes. La columna de 'n_visitas' son las visitas totales en ese mes.

### Duracion de Cada Sesion

In [168]:
diferencia=visits['end_ts']-visits['start_ts']
duracionSesion=pd.DataFrame(columns=['session_time'])
duracionSesion['session_time']=diferencia
duracionSesion['horas']=duracionSesion['session_time'].dt.seconds/3600
duracionSesion

          session_time     horas
0      0 days 00:18:00  0.300000
1      0 days 00:28:00  0.466667
2      0 days 00:00:00  0.000000
3      0 days 00:24:00  0.400000
4      0 days 00:00:00  0.000000
...                ...       ...
359395 0 days 00:00:19  0.005278
359396 0 days 00:00:19  0.005278
359397 0 days 00:00:19  0.005278
359398 0 days 00:00:19  0.005278
359399 0 days 00:00:19  0.005278

[359400 rows x 2 columns]

### Con qué frecuencia los usuarios regresan?

In [169]:
visitStartDatesDifference = visits.sort_values(by=['uid','start_ts_date'])
visitStartDatesDifference['date_difference'] = visitStartDatesDifference.groupby('uid')['start_ts_date'].diff()
visitStartDatesDifference.info()

<class 'pandas.core.frame.DataFrame'>
Index: 359400 entries, 196543 to 132805
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   device           359400 non-null  object
 1   end_ts           359400 non-null  datetime64[ns]
 2   source_id        359400 non-null  int64
 3   start_ts         359400 non-null  datetime64[ns]
 4   uid              359400 non-null  uint64
 5   start_ts_date    359400 non-null  object
 6   start_ts_week    359400 non-null  UInt32
 7   start_ts_month   359400 non-null  object
 8   date_difference  131231 non-null  object
dtypes: UInt32(1), datetime64[ns](2), int64(1), object(4), uint64(1)
memory usage: 26.4+ MB

In [170]:
visitStartDatesDifference['date_difference'] = pd.to_timedelta(visitStartDatesDifference['date_difference'])

In [171]:
visitStartDatesDifference.describe()

,end_ts,source_id,start_ts,uid,start_ts_week,date_difference
count,359400,359400.000000,359400,3.594000e+05,359400.0,131231
mean,2017-12-18 06:28:15.036204544,3.750515,2017-12-18 06:17:32.010517760,9.202557e+18,26.970907,28 days 02:33:52.477082396
min,2017-06-01 00:02:00,1.000000,2017-06-01 00:01:00,1.186350e+13,1.0,0 days 00:00:00
25%,2017-10-15 09:45:45,3.000000,2017-10-15 09:41:00,4.613407e+18,11.0,1 days 00:00:00
50%,2017-12-18 18:59:30,4.000000,2017-12-18 18:46:00,9.227413e+18,26.0,5 days 00:00:00
75%,2018-02-28 10:08:15,5.000000,2018-02-28 09:54:00,1.372824e+19,43.0,32 days 00:00:00
max,2018-06-01 01:26:00,10.000000,2018-05-31 23:59:00,1.844668e+19,52.0,363 days 00:00:00
std,NaN,1.917116,NaN,5.298433e+18,16.77392,49 days 17:31:33.195080023

In [172]:
frequency = visitStartDatesDifference['date_difference'].dt.days.mean()
print(frequency)

28.10685737363885

En promedio los usuarios regresan despues de 28 dias.

In [173]:
frequencyCount=visitStartDatesDifference.value_counts(visitStartDatesDifference['date_difference'])
usersNoReturn=frequencyCount.iloc[0]

In [174]:
totalUsers=visitStartDatesDifference['uid'].nunique()
pusersNoReturn=usersNoReturn*100/totalUsers
print("El",pusersNoReturn,'% de personas nunca regresaron')

El 12.662105719883069 % de personas nunca regresaron

## B. Ventas

### B.1 Cuando empieza la gente a comprar?
Analisis de Cohorte

In [175]:
primera_visita_usuario=visits.groupby('uid').agg({'start_ts':'min'}).reset_index()
primera_visita_usuario.columns=['uid','primera_sesion']

In [176]:
primera_visita_usuario['primera_sesion_mes']=pd.to_datetime(primera_visita_usario['primera_sesion'].dt.strftime("%Y-%m-01"))

In [177]:
primera_visita_usuario

                         uid      primera_sesion primera_sesion_mes
0             11863502262781 2018-03-01 17:27:00         2018-03-01
1             49537067089222 2018-02-06 15:55:00         2018-02-01
2            297729379853735 2017-06-07 18:47:00         2017-06-01
3            313578113262317 2017-09-18 22:49:00         2017-09-01
4            325320750514679 2017-09-30 14:29:00         2017-09-01
...                      ...                 ...                ...
228164  18446403737806311543 2017-11-30 03:36:00         2017-11-01
228165  18446424184725333426 2017-12-06 20:32:00         2017-12-01
228166  18446556406699109058 2018-01-01 16:29:00         2018-01-01
228167  18446621818809592527 2017-12-27 13:27:00         2017-12-01
228168  18446676030785672386 2017-10-04 16:01:00         2017-10-01

[228169 rows x 3 columns]

In [178]:
visitas_total=pd.merge(primera_visita_usuario,visits,on='uid',how='inner')

In [ ]:
visitas_full['edad_meses'] (visitas_full['sesion_mes'] - visitas_full['primera_sesion_mes'])/(30 * np.timedelta64(1, 'D'))).astype(int)